export const cssTextProperties = {
    // Font Properties
    fontFamily: {
        displayName: "Font Family",
        category: "typography",
        options: [
            "serif",
            "sans-serif",
            "monospace",
            "cursive",
            "fantasy",
            "system-ui",
            "ui-serif",
            "ui-sans-serif",
            "ui-monospace",
            "ui-rounded",
            "emoji",
            "math",
            "fangsong",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "depends on user agent",
        inputType: "select",
        section: "Font Family",
        show: false,
        active: true,
    },
    fontSize: {
        displayName: "Font Size",
        category: "typography",
        options: [
            "xx-small",
            "x-small",
            "small",
            "medium",
            "large",
            "x-large",
            "xx-large",
            "xxx-large",
            "larger",
            "smaller",
            "inherit",
            "initial",
            "unset",
        ],
        units: [
            "px",
            "em",
            "rem",
            "%",
            "pt",
            "pc",
            "in",
            "cm",
            "mm",
            "ex",
            "ch",
            "vw",
            "vh",
            "vmin",
            "vmax",
        ],
        defaultValue: "medium",
        inputType: "select",
        section: "Font Size",
        show: false,
        active: true,
    },
    fontWeight: {
        displayName: "Font Weight",
        category: "typography",
        options: [
            "normal",
            "bold",
            "bolder",
            "lighter",
            "100",
            "200",
            "300",
            "400",
            "500",
            "600",
            "700",
            "800",
            "900",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Font Weight",
        show: false,
        active: true,
    },
	fontStyle: {
        displayName: "Font Style",
        category: "typography",
        options: [
            "normal",
            "italic",
            "oblique",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none", "deg"],
        defaultValue: "normal",
        inputType: "select",
        section: "Font Style",
        show: false,
        active: true,
    },
    fontVariant: {
        displayName: "Font Variant",
        category: "typography",
        options: [
            "normal",
            "small-caps",
            "all-small-caps",
            "petite-caps",
            "all-petite-caps",
            "unicase",
            "titling-caps",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Font Variant",
        show: false,
        active: true,
    },
    fontStretch: {
        displayName: "Font Stretch",
        category: "typography",
        options: [
            "normal",
            "ultra-condensed",
            "extra-condensed",
            "condensed",
            "semi-condensed",
            "semi-expanded",
            "expanded",
            "extra-expanded",
            "ultra-expanded",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["%"],
        defaultValue: "normal",
        inputType: "select",
        section: "Font Stretch",
        show: false,
        active: true,
    },

    // Text Layout & Spacing
    lineHeight: {
        displayName: "Line Height",
        category: "typography",
        options: ["normal", "inherit", "initial", "unset"],
        units: ["none", "px", "em", "rem", "%"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Layout & Spacing",
        show: false,
        active: true,
    },
    letterSpacing: {
        displayName: "Letter Spacing",
        category: "typography",
        options: ["normal", "inherit", "initial", "unset"],
        units: ["px", "em", "rem", "ch"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Layout & Spacing",
        show: false,
        active: true,
    },
    wordSpacing: {
        displayName: "Word Spacing",
        category: "typography",
        options: ["normal", "inherit", "initial", "unset"],
        units: ["px", "em", "rem", "%"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Layout & Spacing",
        show: false,
        active: true,
    },
    textIndent: {
        displayName: "Text Indent",
        category: "typography",
        options: ["inherit", "initial", "unset"],
        units: ["px", "em", "rem", "%"],
        defaultValue: "0",
        inputType: "select",
        section: "Text Layout & Spacing",
        show: false,
        active: true,
    },

    // Text Alignment & Direction
    textAlign: {
        displayName: "Text Align",
        category: "typography",
        options: [
            "left",
            "right",
            "center",
            "justify",
            "start",
            "end",
            "match-parent",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "start",
        inputType: "select",
        section: "Text Alignment & Direction",
        show: false,
        active: true,
    },
    textAlignLast: {
        displayName: "Text Align Last",
        category: "typography",
        options: [
            "auto",
            "left",
            "right",
            "center",
            "justify",
            "start",
            "end",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "auto",
        inputType: "select",
        section: "Text Alignment & Direction",
        show: false,
        active: true,
    },
    verticalAlign: {
        displayName: "Vertical Align",
        category: "typography",
        options: [
            "baseline",
            "sub",
            "super",
            "text-top",
            "text-bottom",
            "middle",
            "top",
            "bottom",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["px", "em", "rem", "%"],
        defaultValue: "baseline",
        inputType: "select",
        section: "Text Alignment & Direction",
        show: false,
        active: true,
    },
    direction: {
        displayName: "Direction",
        category: "typography",
        options: ["ltr", "rtl", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "ltr",
        inputType: "select",
        section: "Text Alignment & Direction",
        show: false,
        active: true,
    },
    textOrientation: {
        displayName: "Text Orientation",
        category: "typography",
        options: [
            "mixed",
            "upright",
            "sideways",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "mixed",
        inputType: "select",
        section: "Text Alignment & Direction",
        show: false,
        active: true,
    },

    // Text Decoration & Effects
	textDecoration: {
        displayName: "Text Decoration",
        category: "typography",
        options: [
            "none",
            "underline",
            "overline",
            "line-through",
            "blink",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "none",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textDecorationColor: {
        displayName: "Text Decoration Color",
        category: "typography",
        options: [
            "currentColor",
            "transparent",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "currentColor",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textDecorationStyle: {
        displayName: "Text Decoration Style",
        category: "typography",
        options: [
            "solid",
            "double",
            "dotted",
            "dashed",
            "wavy",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "solid",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textDecorationThickness: {
        displayName: "Text Decoration Thickness",
        category: "typography",
        options: ["auto", "from-font", "inherit", "initial", "unset"],
        units: ["px", "em", "rem", "%"],
        defaultValue: "auto",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textUnderlineOffset: {
        displayName: "Text Underline Offset",
        category: "typography",
        options: ["auto", "inherit", "initial", "unset"],
        units: ["px", "em", "rem", "%"],
        defaultValue: "auto",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textShadow: {
        displayName: "Text Shadow",
        category: "typography",
        options: ["none", "inherit", "initial", "unset"],
        units: ["px", "em", "rem"],
        defaultValue: "none",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },
    textTransform: {
        displayName: "Text Transform",
        category: "typography",
        options: [
            "none",
            "capitalize",
            "uppercase",
            "lowercase",
            "full-width",
            "full-size-kana",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "none",
        inputType: "select",
        section: "Text Decoration & Effects",
        show: false,
        active: true,
    },

    // Color & Visibility
    color: {
        displayName: "Color",
        category: "typography",
        options: [
            "currentColor",
            "transparent",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "depends on user agent",
        inputType: "select",
        section: "Color & Visibility",
        show: false,
        active: true,
    },
    opacity: {
        displayName: "Opacity",
        category: "typography",
        options: ["inherit", "initial", "unset"],
        units: ["none", "%"],
        defaultValue: "1",
        inputType: "select",
        section: "Color & Visibility",
        show: false,
        active: true,
    },

    // Text Overflow & Wrapping
    whiteSpace: {
        displayName: "White Space",
        category: "typography",
        options: [
            "normal",
            "nowrap",
            "pre",
            "pre-wrap",
            "pre-line",
            "break-spaces",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },
    wordWrap: {
        displayName: "Word Wrap",
        category: "typography",
        options: ["normal", "break-word", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },
    overflowWrap: {
        displayName: "Overflow Wrap",
        category: "typography",
        options: [
            "normal",
            "anywhere",
            "break-word",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },
    wordBreak: {
        displayName: "Word Break",
        category: "typography",
        options: [
            "normal",
            "break-all",
            "keep-all",
            "break-word",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },
    textOverflow: {
        displayName: "Text Overflow",
        category: "typography",
        options: ["clip", "ellipsis", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "clip",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },
    hyphens: {
        displayName: "Hyphens",
        category: "typography",
        options: [
            "none",
            "manual",
            "auto",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "manual",
        inputType: "select",
        section: "Text Overflow & Wrapping",
        show: false,
        active: true,
    },

    // Advanced Typography
    fontFeatureSettings: {
        displayName: "Font Feature Settings",
        category: "typography",
        options: ["normal", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Advanced Typography",
        show: false,
        active: true,
    },
    fontVariantCaps: {
        displayName: "Font Variant Caps",
        category: "typography",
        options: [
            "normal",
            "small-caps",
            "all-small-caps",
            "petite-caps",
            "all-petite-caps",
            "unicase",
            "titling-caps",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Advanced Typography",
        show: false,
        active: true,
    },
    textRendering: {
        displayName: "Text Rendering",
        category: "typography",
        options: [
            "auto",
            "optimizeSpeed",
            "optimizeLegibility",
            "geometricPrecision",
            "inherit",
            "initial",
            "unset",
        ],
        units: ["none"],
        defaultValue: "auto",
        inputType: "select",
        section: "Advanced Typography",
        show: false,
        active: true,
    },
    fontOpticalSizing: {
        displayName: "Font Optical Sizing",
        category: "typography",
        options: ["auto", "none", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "auto",
        inputType: "select",
        section: "Advanced Typography",
        show: false,
        active: true,
    },
    fontVariationSettings: {
        displayName: "Font Variation Settings",
        category: "typography",
        options: ["normal", "inherit", "initial", "unset"],
        units: ["none"],
        defaultValue: "normal",
        inputType: "select",
        section: "Advanced Typography",
        show: false,
        active: true,
    },
};

export default cssTextProperties;
