import type { Metadata } from "next";
import { StoreProvider } from "./StoreProvider";
import "./configs/globalStyles.scss";
import { montserrat, manrope } from "./configs/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<StoreProvider>
			<html lang="en">
				<body className={`${montserrat.variable} ${manrope.variable}`}>
					{children}
				</body>
			</html>
		</StoreProvider>
	);
}
